DROP TABLE IF EXISTS CONTACT;

CREATE TABLE CONTACT (
  ID INT PRIMARY KEY AUTO_INCREMENT,
  NAME VARCHAR(90) NOT NULL,
  COUNT INT,
  BUY_DATE TIMESTAMP NOT NULL,
  VERSION INT DEFAULT 0,
  UNIQUE UQ_NAME_DATE (NAME, BUY_DATE)
)